# Generated by Django 4.2.11 on 2024-03-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='itunes_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
