# Generated by Django 4.2.11 on 2024-03-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0002_artist_itunes_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='artist_image',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='avatar',
        ),
        migrations.AddField(
            model_name='artist',
            name='avatar_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
