# Generated by Django 4.2.11 on 2024-03-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0003_remove_artist_artist_image_remove_artist_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
