# Generated by Django 4.2.11 on 2024-03-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0004_album_cover_image_alter_track_audio_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
    ]
