# Generated by Django 4.2.11 on 2024-03-22 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0004_alter_album_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
