# Generated by Django 4.2.11 on 2024-03-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0006_artist_artist_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media/artists_avatar'),
        ),
    ]
