# Generated by Django 4.2.11 on 2024-03-17 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0008_album_tracks_artist_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='tracks',
        ),
    ]
