# Generated by Django 4.2.11 on 2024-03-19 15:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_app', '0012_trackuserrelation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrackUserRelation',
            new_name='TrackUserRelationship',
        ),
    ]
