# Generated by Django 4.2.11 on 2024-03-19 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0013_rename_trackuserrelation_trackuserrelationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumuserrelationship',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_album', to='music_app.album'),
        ),
        migrations.AlterField(
            model_name='trackuserrelationship',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_track', to='music_app.track'),
        ),
    ]
