services:
  web-app:
    build:
      context: ../music-library
    ports:
      - "8000:8000"
    volumes:
      - ./music_library:/music_library
    environment:
      - DB_HOST=database
      - DB_NAME=db_name
      - DB_USER=db_user
      - DB_PASS=pass
    depends_on:
      - database

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

  database:
    image: postgres:15.6-alpine
    environment:
      - POSTGRES_DB=db_name
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=pass