services:
  web-app:
    build:
      context: ../Music-library-app
    ports:
      - "8000:8000"
    volumes:
      - ./music_library:/music_library
    environment:
      - DB_HOST=database
      - DB_NAME=db_name
      - DB_USER=db_user
      - DB_PASS=pass
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - database
      - redis

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

  database:
    image: postgres:15.6-alpine
    environment:
      - POSTGRES_DB=db_name
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=pass

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data